---
apiVersion: v1
kind: Service
metadata:
  name: #{SERVICE_NAME}#-service
  namespace: #{NAMESPACE}#
  labels:
    app: #{SERVICE_NAME}#-app
spec:
  type: ClusterIP
  selector:
    app: #{SERVICE_NAME}#-app
  ports:
  - port: #{SERVICE_PORT}#
    protocol: TCP
    targetPort: #{SERVICE_PORT}#
    name: http
    
 ##random change to test the permissions of GitHub App
