name: Multi-Domain Deployment

on:
  push:
    branches:
      - 'feature/multi-domain'

env:
  domain_list: "de,co.uk,fr,ca,es,it,nl,dk,se"

jobs:
  multi-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: '1'
      
      - name: Generate Manifests
        shell: bash
        run: |
          cd k8s/deployment
          for i in $(echo ${{ env.domain_list }} | sed "s/,/ /g")
          do
            export INGRESS_FQDN_MULTIDOMAIN="www.remix.$i.qa.jf.techstyle.tech"
            export INGRESS_NAME="remix"
            export SERVICE_NAME="remix-develop"
            export SERVICE_PORT="80"
            envsubst < multi-domain-template.yaml >> multidomain-$i.yaml
          done
          ls
          cat multidomain-*.yaml