name: Sanity Tests
run-name: Running Sanity Tests

on:
  pull_request_review:
    types: [submitted]

jobs:
  sanity-tests:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Echo the Output
        shell: bash
        run: |
          echo "Running Sanity Tests Now"
      # - name: Checkout Code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      # - name: Set Branch Name
      #   shell: bash
      #   run: |
      #     echo "branch_name=$(echo ${{ github.event.pull_request.head.ref || github.ref_name }})" >> $GITHUB_ENV

      # - name: Create sanitized Subdomain Prefix
      #   id: subdomain-sanitize
      #   uses: LarsenLP/actions-find-and-replace-string@v3
      #   with:
      #     source: "www.remix.com"
      #     find: '.'
      #     replace: '-'

      # - name: Echo the output
      #   shell: bash 
      #   run: echo ${{ steps.subdomain-sanitize.outputs.value }}
        
      # - name: Set the value
      #   id: step_one
      #   run: |
      #     echo "branch_sanitize=$(echo ${{ github.event.pull_request.head.ref || github.ref_name }} | sed -e 's/_/-/g' -e 's/\//-/g' | awk '{print tolower($0)}')" >> $GITHUB_ENV
      # - name: Use the value
      #   id: step_two
      #   run: |
      #     echo "${{ env.branch_sanitize }}"
      #     echo "${{ env.branch_name }}"
  
#       - name: Check the deployed service URL
#         uses: jtalk/url-health-check-action@v2
#         with:
#           # Check the following URLs one by one sequentially
#           url: https://www.googlejsxcjasd.com/
#           # Follow redirects, or just report success on 3xx status codes
#           follow-redirect: false # Optional, defaults to "false"
#           # Fail this action after this many failed attempts
#           max-attempts: 3 # Optional, defaults to 1
#           # Delay between retries
#           retry-delay: 5s # Optional, only applicable to max-attempts > 1
#           # Retry all errors, including 404. This option might trigger curl upgrade.
#           retry-all: false # Optional, defaults to "false"
          
#       - uses: cschleiden/replace-tokens@v1
#         with:
#           files: '["k8s/deployment/kube.yaml"]'
#         env:
#           NAMESPACE: spa-qa
#           SECRET: ${{ env.SECRET }}
          
#       - name: Check the contents
#         run: cat "k8s/deployment/kube.yaml"
        
#       - name: Check Branch Name
#         run: echo ${{ github.event.pull_request.head.ref }}
        
      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.18.0
      #   with:
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "${{ github.workflow }} Started Triggered by ${{ github.actor }} on branch ${{ github.ref_name}}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
