name: Trigger Sanity Tests

on:
  pull_request_review:
    types: [submitted]

jobs:
  sanity-tests:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Echo the Output
        shell: bash
        run: |
          echo "Running Sanity Tests Now"
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # - name: Checkout Code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      # - name: Set Branch Name
      #   shell: bash
      #   run: |
      #     echo "branch_name=$(echo ${{ github.event.pull_request.head.ref || github.ref_name }})" >> $GITHUB_ENV
