name: Run on PR Open and sync

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Run on PR Open and sync
    runs-on: ubuntu-latest
    steps:
      - name: Echo the Output
        shell: bash
        run: |
          echo "Running the build"