name: WIP

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  WIP:
    name: WIP
    runs-on: ubuntu-latest
    steps:
      - name: WIP Action
        uses: wow-actions/wip@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          labels: 'do-not-merge', 'do not merge' , 'work in progress', 'wip', 'work-in-progress' , 'fixup'
          keywords: 'do-not-merge', 'do not merge' , 'work in progress', 'wip', 'work-in-progress' , 'fixup'
          wip_description: 'work in progress'
          ready_description: 'ready for review'